<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Во время установки Rights произошла ошибка.',
  'Application authorization manager must extend the RDbAuthManager class.' => 'Менеджер авторизации приложения должен расширять класс RDbAuthManager.',
  'Application web user must extend the RWebUser class.' => 'Веб-пользователь приложения должен расширять класс RWebUser.',
  'Congratulations!' => 'Поздравляем!',
  'Error' => 'Ошибка',
  'Install Rights' => 'Установка Rights',
  'No' => 'Нет',
  'Notice: All your existing data will be lost.' => 'Внимание: все ваши существующие данные будут потеряны.',
  'Please confirm if you wish to reinstall.' => 'Пожалуйста, подтвердите, что хотите переустановить.',
  'Please try again or consult the documentation.' => 'Пожалуйста, попробуйте еще раз или обратитесь к документации.',
  'Rights has been installed succesfully.' => 'Модуль Rights был успешно установлен.',
  'Rights is already installed!' => 'Модуль Rights уже установлен!',
  'Yes' => 'Да',
  'You can start by generating your authorization items' => 'Вы можете начать с генерации ваших элементов авторизации.',
  'You must be logged in to install Rights.' => 'Для установки Rights вы должны войти в систему.',
  'here' => 'здесь',
);
